In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_vietnam = pd.read_excel(r'alldatasets.xlsx',sheet_name='Vietnam')

In [3]:
df_vietnam.head()

,childid,country,height,stunting_2cat,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn,earn_usd
0,VN011001,Vietnam,170.000000,1,12.0,-0.493371,5.0,NaN,12.0,1,91,5,0.561111,1,1,0.0,0.000000
1,VN011002,Vietnam,153.500000,1,12.0,-0.795860,15.0,3.0,9.0,0,92,6,0.546296,1,1,0.0,0.000000
2,VN011003,Vietnam,158.000000,1,8.0,-1.421140,5.0,7.0,6.0,0,100,5,0.455556,2,1,19200000.0,875.313416
3,VN011004,Vietnam,157.500000,0,12.0,-0.539453,10.0,0.0,9.0,0,94,6,0.592593,5,1,4600000.0,209.710495
4,VN011005,Vietnam,157.600006,0,16.0,-0.297198,10.0,4.0,0.0,0,95,5,0.466667,5,1,2800000.0,127.649872

In [4]:
df_vietnam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   childid        801 non-null    object
 1   country        801 non-null    object
 2   height         801 non-null    float64
 3   stunting_2cat  801 non-null    int64
 4   EDUYRS2        800 non-null    float64
 5   z_score        783 non-null    float64
 6   timeschool     770 non-null    float64
 7   agegapr1       754 non-null    float64
 8   momeduyrsr1    783 non-null    float64
 9   chsexr1        801 non-null    int64
 10  agemonr1       801 non-null    int64
 11  hhsizer1       801 non-null    int64
 12  wi_newr1       800 non-null    float64
 13  job_cat        801 non-null    int64
 14  pvt_sector     801 non-null    int64
 15  earn           801 non-null    float64
 16  earn_usd       801 non-null    float64
dtypes: float64(9), int64(6), object(2)
memory usage: 106.5+ KB

In [5]:
df_vietnam.describe()

,height,stunting_2cat,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn,earn_usd
count,801.000000,801.000000,800.000000,783.000000,770.000000,754.000000,783.000000,801.000000,801.000000,801.000000,800.000000,801.00000,801.0,8.010000e+02,801.000000
mean,161.149813,0.292135,11.305625,-0.039324,16.112987,3.038462,5.136654,0.496879,95.704120,4.961298,0.447439,4.06367,1.0,1.100511e+07,501.714770
std,7.640439,0.455028,3.274761,0.968907,10.163755,2.821348,4.137097,0.500303,3.290303,1.588946,0.206297,1.57232,0.0,4.108069e+07,1872.837245
min,141.500000,0.000000,0.000000,-3.622698,0.000000,0.000000,0.000000,0.000000,82.000000,2.000000,0.004630,1.00000,1.0,0.000000e+00,0.000000
25%,155.100006,0.000000,9.000000,-0.574352,10.000000,1.000000,0.000000,0.000000,93.000000,4.000000,0.291667,3.00000,1.0,2.800000e+06,127.649872
50%,161.000000,0.000000,12.000000,0.068745,15.000000,2.000000,6.000000,0.000000,96.000000,5.000000,0.462963,5.00000,1.0,4.500000e+06,205.151581
75%,166.800003,1.000000,12.500000,0.581687,20.000000,4.000000,9.000000,1.000000,98.000000,6.000000,0.587037,5.00000,1.0,7.000000e+06,319.124664
max,187.199997,1.000000,16.500000,2.301673,77.000000,25.000000,12.000000,1.000000,102.000000,17.000000,0.972222,5.00000,1.0,9.600000e+08,43765.667970

In [6]:
df_vietnam=df_vietnam.astype({"chsexr1": 'object', "job_cat": 'object', "pvt_sector": 'object',"stunting_2cat": 'object'})

In [7]:
df_vietnam.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
timeschool       float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1           int64
hhsizer1           int64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn             float64
earn_usd         float64
dtype: object

In [8]:
df_outlier=df_vietnam.copy()

In [9]:
df_outlier.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
timeschool       float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1           int64
hhsizer1           int64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn             float64
earn_usd         float64
dtype: object

In [10]:
total = df_outlier.isnull().sum().sort_values(ascending=False)
percent = (df_outlier.isnull().sum()/df_outlier.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Missing Percent'])
missing_data['Missing Percent'] = missing_data['Missing Percent'].apply(lambda x: x * 100)
missing_data.loc[missing_data['Missing Percent'] > 95]

Empty DataFrame
Columns: [Total, Missing Percent]
Index: []

In [11]:
df_outlier=df_outlier.select_dtypes(include=['int64','floating'])

In [12]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
timeschool     float64
agegapr1       float64
momeduyrsr1    float64
agemonr1         int64
hhsizer1         int64
wi_newr1       float64
earn           float64
earn_usd       float64
dtype: object

In [13]:
import warnings

warnings.filterwarnings('ignore')

In [14]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
timeschool     float64
agegapr1       float64
momeduyrsr1    float64
agemonr1         int64
hhsizer1         int64
wi_newr1       float64
earn           float64
earn_usd       float64
dtype: object

In [15]:
#sns.pairplot(df_outlier)

# Outlier Cappping

In [16]:
def cap_data(df):
    for col in df.columns:
        print("capping the ",col)
        if (((df[col].dtype)=='float64') | ((df[col].dtype)=='int64') | ((df[col].dtype)=='float32')):
            percentiles = df[col].quantile([0.01,0.99]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
        else:
            df[col]=df[col]
    return df

In [17]:
final_df=cap_data(df_outlier)

capping the  height
capping the  EDUYRS2
capping the  z_score
capping the  timeschool
capping the  agegapr1
capping the  momeduyrsr1
capping the  agemonr1
capping the  hhsizer1
capping the  wi_newr1
capping the  earn
capping the  earn_usd

In [18]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

In [19]:
df_vietnam=df_vietnam.drop(['childid','country'],axis=1)

In [20]:
all_category_features=df_vietnam.select_dtypes(include='object')

In [21]:
all_category_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  801 non-null    object
 1   chsexr1        801 non-null    object
 2   job_cat        801 non-null    object
 3   pvt_sector     801 non-null    object
dtypes: object(4)
memory usage: 25.2+ KB

# KNN for Categories

In [22]:
mm = MinMaxScaler()

def find_category_mappings(df, variable):
    return {k: i for i, k in enumerate(df[variable].dropna().unique(), 0)}

def integer_encode(df , variable, ordinal_mapping):
    df[variable] = df[variable].map(ordinal_mapping)

mappin = dict()
def imputation(df1 , cols):
    df = df1.copy()
    #Encoding dict &amp; Removing nan    
    #mappin = dict()
    for variable in cols:
        mappings = find_category_mappings(df, variable)
        mappin[variable] = mappings

    #Apply mapping
    for variable in cols:
        integer_encode(df, variable, mappin[variable])  

    #Minmaxscaler and KNN imputation 
    sca = mm.fit_transform(df)
    knn_imputer = KNNImputer()
    knn = knn_imputer.fit_transform(sca)
    df.iloc[:,:] = mm.inverse_transform(knn)
    for i in df.columns : 
        df[i] = round(df[i]).astype('int')

    #Inverse transform
    for i in cols:
        inv_map = {v: k for k, v in mappin[i].items()}
        df[i] = df[i].map(inv_map)
    return df

In [23]:
df_cat_imp=imputation(all_category_features,['stunting_2cat','chsexr1','job_cat','pvt_sector'])

In [24]:
df_cat_imp.isnull().sum().sort_values(ascending = False)

pvt_sector       0
job_cat          0
chsexr1          0
stunting_2cat    0
dtype: int64

In [25]:
df_cat_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  801 non-null    int64
 1   chsexr1        801 non-null    int64
 2   job_cat        801 non-null    int64
 3   pvt_sector     801 non-null    int64
dtypes: int64(4)
memory usage: 25.2 KB

In [26]:
#df_cat_imp.to_csv(r'C:\Users\rramr\OneDrive\Desktop\Modern Scientist Global\Peru\df_knn_before.csv', encoding='utf-8', index=True)

In [27]:
#all_category_features=df_et.select_dtypes(include='o')

In [28]:
#cat_dummies = pd.get_dummies(all_category_features, dummy_na=True)
#cat_dummies.head()

# KNN for numerics

In [29]:
df_knn=final_df.copy()

In [30]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df_num_imp = pd.DataFrame(imputer.fit_transform(df_knn),columns = df_knn.columns)

In [31]:
df_num_imp.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd
0,170.000000,12.0,-0.493371,5.0,1.8,12.0,91.0,5.0,0.561111,0.0,0.000000
1,153.500000,12.0,-0.795860,15.0,3.0,9.0,92.0,6.0,0.546296,0.0,0.000000
2,158.000000,8.0,-1.421140,5.0,7.0,6.0,100.0,5.0,0.455556,19200000.0,875.313416
3,157.500000,12.0,-0.539453,10.0,0.0,9.0,94.0,6.0,0.592593,4600000.0,209.710495
4,157.600006,16.0,-0.297198,10.0,4.0,0.0,95.0,5.0,0.466667,2800000.0,127.649872

In [32]:
df_outlier_concat = pd.concat([df_num_imp, df_cat_imp], axis=1)
df_outlier_concat.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,170.000000,12.0,-0.493371,5.0,1.8,12.0,91.0,5.0,0.561111,0.0,0.000000,1,1,1,1
1,153.500000,12.0,-0.795860,15.0,3.0,9.0,92.0,6.0,0.546296,0.0,0.000000,1,0,1,1
2,158.000000,8.0,-1.421140,5.0,7.0,6.0,100.0,5.0,0.455556,19200000.0,875.313416,1,0,2,1
3,157.500000,12.0,-0.539453,10.0,0.0,9.0,94.0,6.0,0.592593,4600000.0,209.710495,0,0,5,1
4,157.600006,16.0,-0.297198,10.0,4.0,0.0,95.0,5.0,0.466667,2800000.0,127.649872,0,0,5,1

In [33]:
df_outlier_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   height         801 non-null    float64
 1   EDUYRS2        801 non-null    float64
 2   z_score        801 non-null    float64
 3   timeschool     801 non-null    float64
 4   agegapr1       801 non-null    float64
 5   momeduyrsr1    801 non-null    float64
 6   agemonr1       801 non-null    float64
 7   hhsizer1       801 non-null    float64
 8   wi_newr1       801 non-null    float64
 9   earn           801 non-null    float64
 10  earn_usd       801 non-null    float64
 11  stunting_2cat  801 non-null    int64
 12  chsexr1        801 non-null    int64
 13  job_cat        801 non-null    int64
 14  pvt_sector     801 non-null    int64
dtypes: float64(11), int64(4)
memory usage: 94.0 KB

In [34]:
df_outlier_concat=df_outlier_concat.astype({"stunting_2cat": 'int64'})

In [35]:
df_outlier_concat.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,170.000000,12.0,-0.493371,5.0,1.8,12.0,91.0,5.0,0.561111,0.0,0.000000,1,1,1,1
1,153.500000,12.0,-0.795860,15.0,3.0,9.0,92.0,6.0,0.546296,0.0,0.000000,1,0,1,1
2,158.000000,8.0,-1.421140,5.0,7.0,6.0,100.0,5.0,0.455556,19200000.0,875.313416,1,0,2,1
3,157.500000,12.0,-0.539453,10.0,0.0,9.0,94.0,6.0,0.592593,4600000.0,209.710495,0,0,5,1
4,157.600006,16.0,-0.297198,10.0,4.0,0.0,95.0,5.0,0.466667,2800000.0,127.649872,0,0,5,1

In [36]:
df_knn_imp=df_outlier_concat.copy()

In [37]:
import statsmodels.api as sm

# cognition

In [38]:
#cognition

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.061
Model:                            OLS   Adj. R-squared:                  0.060
Method:                 Least Squares   F-statistic:                     52.21
Date:                Wed, 12 May 2021   Prob (F-statistic):           1.16e-12
Time:                        14:39:46   Log-Likelihood:                -1062.8
No. Observations:                 801   AIC:                             2130.
Df Residuals:                     799   BIC:                             2139.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.1149      0.038      2.995      0.003       0.040       0.190
stunting_2cat    -0.5127      0.071     -7.226      0.000      -0.652      -0.373
==============================================================================
Omnibus:                       22.392   Durbin-Watson:                   1.423
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.743
Skew:                          -0.422   Prob(JB):                     6.99e-06
Kurtosis:                       3.025   Cond. No.                         2.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# height

In [39]:
#Height

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.091
Model:                            OLS   Adj. R-squared:                  0.090
Method:                 Least Squares   F-statistic:                     80.09
Date:                Wed, 12 May 2021   Prob (F-statistic):           2.46e-18
Time:                        14:39:46   Log-Likelihood:                -2714.2
No. Observations:                 801   AIC:                             5432.
Df Residuals:                     799   BIC:                             5442.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           162.5959      0.301    539.491      0.000     162.004     163.188
stunting_2cat    -4.9904      0.558     -8.950      0.000      -6.085      -3.896
==============================================================================
Omnibus:                       51.857   Durbin-Watson:                   2.087
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               19.464
Skew:                           0.067   Prob(JB):                     5.94e-05
Kurtosis:                       2.248   Cond. No.                         2.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# education

In [40]:
#education

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.032
Method:                 Least Squares   F-statistic:                     27.38
Date:                Wed, 12 May 2021   Prob (F-statistic):           2.13e-07
Time:                        14:39:46   Log-Likelihood:                -2063.1
No. Observations:                 801   AIC:                             4130.
Df Residuals:                     799   BIC:                             4140.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            11.6949      0.134     87.473      0.000      11.432      11.957
stunting_2cat    -1.2945      0.247     -5.233      0.000      -1.780      -0.809
==============================================================================
Omnibus:                       13.927   Durbin-Watson:                   1.780
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                8.380
Skew:                           0.056   Prob(JB):                       0.0151
Kurtosis:                       2.512   Cond. No.                         2.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# cognition covariates

In [41]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.308
Method:                 Least Squares   F-statistic:                     51.76
Date:                Wed, 12 May 2021   Prob (F-statistic):           8.46e-61
Time:                        14:39:46   Log-Likelihood:                -937.49
No. Observations:                 801   AIC:                             1891.
Df Residuals:                     793   BIC:                             1928.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.1664      0.823      0.202      0.840      -1.450       1.782
stunting_2cat    -0.2604      0.063     -4.134      0.000      -0.384      -0.137
agemonr1         -0.0055      0.009     -0.645      0.519      -0.022       0.011
chsexr1          -0.2162      0.056     -3.875      0.000      -0.326      -0.107
agegapr1          0.0037      0.011      0.345      0.730      -0.017       0.025
momeduyrsr1       0.0370      0.008      4.598      0.000       0.021       0.053
hhsizer1         -0.0831      0.020     -4.250      0.000      -0.121      -0.045
wi_newr1          1.6200      0.156     10.395      0.000       1.314       1.926
==============================================================================
Omnibus:                       15.302   Durbin-Watson:                   1.669
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.941
Skew:                          -0.342   Prob(JB):                     0.000346
Kurtosis:                       2.904   Cond. No.                     2.86e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Height covariates

In [42]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.604
Model:                            OLS   Adj. R-squared:                  0.600
Method:                 Least Squares   F-statistic:                     172.7
Date:                Wed, 12 May 2021   Prob (F-statistic):          8.95e-155
Time:                        14:39:47   Log-Likelihood:                -2381.5
No. Observations:                 801   AIC:                             4779.
Df Residuals:                     793   BIC:                             4817.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           159.5549      4.994     31.947      0.000     149.751     169.359
stunting_2cat    -5.6366      0.382    -14.748      0.000      -6.387      -4.886
agemonr1         -0.0151      0.052     -0.289      0.772      -0.118       0.087
chsexr1          10.7887      0.339     31.869      0.000      10.124      11.453
agegapr1         -0.0069      0.065     -0.107      0.915      -0.134       0.120
momeduyrsr1       0.0557      0.049      1.141      0.254      -0.040       0.152
hhsizer1         -0.1704      0.119     -1.437      0.151      -0.403       0.062
wi_newr1         -0.2371      0.945     -0.251      0.802      -2.093       1.619
==============================================================================
Omnibus:                        2.269   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.322   Jarque-Bera (JB):                2.052
Skew:                          -0.035   Prob(JB):                        0.358
Kurtosis:                       2.762   Cond. No.                     2.86e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# education covariates

In [43]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.275
Model:                            OLS   Adj. R-squared:                  0.269
Method:                 Least Squares   F-statistic:                     42.96
Date:                Wed, 12 May 2021   Prob (F-statistic):           1.65e-51
Time:                        14:39:47   Log-Likelihood:                -1947.9
No. Observations:                 801   AIC:                             3912.
Df Residuals:                     793   BIC:                             3949.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             7.0246      2.906      2.417      0.016       1.320      12.730
stunting_2cat    -0.4788      0.222     -2.153      0.032      -0.915      -0.042
agemonr1          0.0251      0.030      0.825      0.410      -0.035       0.085
chsexr1          -1.0408      0.197     -5.283      0.000      -1.428      -0.654
agegapr1         -0.0257      0.038     -0.684      0.494      -0.100       0.048
momeduyrsr1       0.2226      0.028      7.833      0.000       0.167       0.278
hhsizer1         -0.0541      0.069     -0.784      0.433      -0.190       0.081
wi_newr1          3.9324      0.550      7.147      0.000       2.852       5.012
==============================================================================
Omnibus:                        8.050   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.018   Jarque-Bera (JB):                7.315
Skew:                           0.181   Prob(JB):                       0.0258
Kurtosis:                       2.702   Cond. No.                     2.86e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""